<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite58ddc859fdf625bb6684be217612442
{
    public static $prefixLengthsPsr4 = array (
        'K' =>
        array (
            'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\' => 48,
            'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\' => 49,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/woocommerce/src',
        ),
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/settings-page/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Addons' => __DIR__ . '/..' . '/krokedil/settings-page/src/Addons.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Gateway' => __DIR__ . '/..' . '/krokedil/settings-page/src/Gateway.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Navigation' => __DIR__ . '/..' . '/krokedil/settings-page/src/Navigation.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Page' => __DIR__ . '/..' . '/krokedil/settings-page/src/Page.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\SettingsPage' => __DIR__ . '/..' . '/krokedil/settings-page/src/SettingsPage.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Support' => __DIR__ . '/..' . '/krokedil/settings-page/src/Support.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Layout' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Layout.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Sidebar' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Sidebar.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Singleton' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Singleton.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Subsection' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Subsection.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Base' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Base.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\Cart' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/Cart.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartCustomer.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineCoupon.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineFee.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineItem.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineShipping.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Abstracts\\AbstractGiftCardCompatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Abstracts/AbstractGiftCardCompatibility.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Compatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Compatibility.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\PWGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/PWGiftCards.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\SmartCoupons' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/SmartCoupons.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\WCGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/WCGiftCards.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\YITHGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/YITHGiftCards.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\CustomerData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/CustomerData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\CompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/CompatibilityInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\GiftCardCompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/GiftCardCompatibilityInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\MetaboxInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/MetaboxInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\KrokedilWooCommerce' => __DIR__ . '/..' . '/krokedil/woocommerce/src/KrokedilWooCommerce.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderLineData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderLineData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderMetabox' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderMetabox.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderUtility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderUtility.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\Order' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/Order.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderCustomer.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLine' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLine.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineCoupon.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineFee.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineItem.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineShipping.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApi' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApi.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiCustomer.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineCoupon.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineFee.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineItem.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineShipping.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Subscription' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Subscription.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite58ddc859fdf625bb6684be217612442::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite58ddc859fdf625bb6684be217612442::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite58ddc859fdf625bb6684be217612442::$classMap;

        }, null, ClassLoader::class);
    }
}
