<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit436a49ab090b295979368efe582b35be
{
    public static $prefixLengthsPsr4 = array (
        'K' =>
        array (
            'KrokedilKlarnaCheckoutDeps\\Psr\\Container\\' => 41,
            'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\' => 48,
            'KrokedilKlarnaCheckoutDeps\\Krokedil\\Support\\' => 44,
            'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\' => 45,
            'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\' => 49,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'KrokedilKlarnaCheckoutDeps\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/woocommerce/src',
        ),
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Support\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/support/src',
        ),
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/shipping/src',
        ),
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/settings-page/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Addons' => __DIR__ . '/..' . '/krokedil/settings-page/src/Addons.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Gateway' => __DIR__ . '/..' . '/krokedil/settings-page/src/Gateway.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Navigation' => __DIR__ . '/..' . '/krokedil/settings-page/src/Navigation.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Page' => __DIR__ . '/..' . '/krokedil/settings-page/src/Page.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\SettingsPage' => __DIR__ . '/..' . '/krokedil/settings-page/src/SettingsPage.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Support' => __DIR__ . '/..' . '/krokedil/settings-page/src/Support.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Layout' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Layout.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Sidebar' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Sidebar.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Singleton' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Singleton.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\SettingsPage\\Traits\\Subsection' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Subsection.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\AJAX' => __DIR__ . '/..' . '/krokedil/shipping/src/AJAX.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Admin\\EditOrderPage' => __DIR__ . '/..' . '/krokedil/shipping/src/Admin/EditOrderPage.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Assets' => __DIR__ . '/..' . '/krokedil/shipping/src/Assets.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Calculations' => __DIR__ . '/..' . '/krokedil/shipping/src/Calculations.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Container\\Container' => __DIR__ . '/..' . '/krokedil/shipping/src/Container/Container.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Container\\Exceptions\\ContainerException' => __DIR__ . '/..' . '/krokedil/shipping/src/Container/Exceptions/ContainerException.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Container\\Exceptions\\NotFoundException' => __DIR__ . '/..' . '/krokedil/shipping/src/Container/Exceptions/NotFoundException.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Frontend\\PickupPointSelect' => __DIR__ . '/..' . '/krokedil/shipping/src/Frontend/PickupPointSelect.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Frontend\\ShippingRateOutput' => __DIR__ . '/..' . '/krokedil/shipping/src/Frontend/ShippingRateOutput.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Interfaces\\PickupPointServiceInterface' => __DIR__ . '/..' . '/krokedil/shipping/src/Interfaces/PickupPointServiceInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Interfaces\\ShippingRateServiceInterface' => __DIR__ . '/..' . '/krokedil/shipping/src/Interfaces/ShippingRateServiceInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\PickupPoint\\Address' => __DIR__ . '/..' . '/krokedil/shipping/src/PickupPoint/Address.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\PickupPoint\\Coordinates' => __DIR__ . '/..' . '/krokedil/shipping/src/PickupPoint/Coordinates.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\PickupPoint\\EstimatedTimeOfArrival' => __DIR__ . '/..' . '/krokedil/shipping/src/PickupPoint/EstimatedTimeOfArrival.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\PickupPoint\\OpenHours' => __DIR__ . '/..' . '/krokedil/shipping/src/PickupPoint/OpenHours.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\PickupPoint\\PickupPoint' => __DIR__ . '/..' . '/krokedil/shipping/src/PickupPoint/PickupPoint.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\PickupPoints' => __DIR__ . '/..' . '/krokedil/shipping/src/PickupPoints.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\SessionHandler' => __DIR__ . '/..' . '/krokedil/shipping/src/SessionHandler.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\ShippingRate' => __DIR__ . '/..' . '/krokedil/shipping/src/ShippingRate.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Traits\\ArrayFormat' => __DIR__ . '/..' . '/krokedil/shipping/src/Traits/ArrayFormat.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Traits\\JsonFormat' => __DIR__ . '/..' . '/krokedil/shipping/src/Traits/JsonFormat.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Shipping\\Traits\\RateData' => __DIR__ . '/..' . '/krokedil/shipping/src/Traits/RateData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Support\\Logger' => __DIR__ . '/..' . '/krokedil/support/src/Logger.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\Support\\SystemReport' => __DIR__ . '/..' . '/krokedil/support/src/SystemReport.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Base' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Base.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\Cart' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/Cart.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartCustomer.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineCoupon.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineFee.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineItem.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineShipping.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Abstracts\\AbstractGiftCardCompatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Abstracts/AbstractGiftCardCompatibility.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Compatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Compatibility.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\PWGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/PWGiftCards.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\SmartCoupons' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/SmartCoupons.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\WCGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/WCGiftCards.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\YITHGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/YITHGiftCards.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\CustomerData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/CustomerData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\CompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/CompatibilityInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\GiftCardCompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/GiftCardCompatibilityInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\MetaboxInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/MetaboxInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\KrokedilWooCommerce' => __DIR__ . '/..' . '/krokedil/woocommerce/src/KrokedilWooCommerce.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderLineData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderLineData.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderMetabox' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderMetabox.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\OrderUtility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderUtility.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\Order' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/Order.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderCustomer.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLine' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLine.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineCoupon.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineFee.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineItem.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineShipping.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApi' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApi.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiCustomer.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineCoupon.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineFee.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineItem.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineShipping.php',
        'KrokedilKlarnaCheckoutDeps\\Krokedil\\WooCommerce\\Subscription' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Subscription.php',
        'KrokedilKlarnaCheckoutDeps\\Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'KrokedilKlarnaCheckoutDeps\\Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit436a49ab090b295979368efe582b35be::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit436a49ab090b295979368efe582b35be::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit436a49ab090b295979368efe582b35be::$classMap;

        }, null, ClassLoader::class);
    }
}
